[global]
    frame_color = "#4B3D43"

[urgency_low]
    background = "#44373A"
    foreground = "#DFC8B1"
    frame_color = "#908A7B"
    highlight = "#AA9D8A"

[urgency_normal]
    background = "#352B2D"
    foreground = "#F1DBC2"
    frame_color = "#4B3D43"
    highlight = "#CCB7A0"

[urgency_critical]
    background = "#352B2D"
    foreground = "#F1DBC2"
    frame_color = "#CCB7A0"
    highlight = "#CCB7A0"
