[global]
    frame_color = "#CCB7A0"

[urgency_low]
    background = "#DFC8B1"
    foreground = "#44373A"
    frame_color = "#857974"
    highlight = "#625458"

[urgency_normal]
    background = "#F1DBC2"
    foreground = "#352B2D"
    frame_color = "#CCB7A0"
    highlight = "#4B3D43"

[urgency_critical]
    background = "#F1DBC2"
    foreground = "#352B2D"
    frame_color = "#4B3D43"
    highlight = "#4B3D43"
