hl.config({ autogenerated = false })

local cfg = (os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config")) .. "/hypr"
package.path = cfg .. "/?.lua;" .. cfg .. "/?/init.lua;" .. (package.path or "")

local function load(rel, required)
    local path = cfg .. "/" .. rel
    local ok, err = pcall(dofile, path)
    if ok then
        return
    end
    io.stderr:write("[aurora] hypr load failed " .. path .. ": " .. tostring(err) .. "\n")
    if required then
        error(err)
    end
end

load("config/programs.lua")
load("config/monitors.lua", true)
load("config/workspaces.lua")
load("config/environment.lua")
load("config/cursor-env.lua")
load("config/decorations.lua")
load("config/theme.lua")
load("config/animations.lua")
load("config/input.lua")
load("config/autostart.lua")
load("config/keybinds.lua", true)
load("config/windows.lua")
load("config/layerules.lua")
load("config/permissions.lua")
