hl.config({ autogenerated = false })

local cfg = (os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config")) .. "/hypr"
package.path = cfg .. "/?.lua;" .. cfg .. "/?/init.lua;" .. (package.path or "")

local function load(rel)
    dofile(cfg .. "/" .. rel)
end

load("config/programs.lua")
load("config/monitors.lua")
load("config/workspaces.lua")
load("config/environment.lua")
load("config/decorations.lua")
load("config/theme.lua")
load("config/animations.lua")
load("config/input.lua")
load("config/autostart.lua")
load("config/keybinds.lua")
load("config/windows.lua")
load("config/layerules.lua")
load("config/permissions.lua")

-- Load after permissions so hyprctl can inject csgo-vulkan-fix.
hl.exec_cmd((os.getenv("HOME") or "/home/dd") .. "/.config/scripts/ow-stretch-plugin.sh")
