# Shared helpers for Steam launch wrappers. Sourced, not executed.

# Hyprland owns XWayland (:0, rootless). Never spawn a second X server.
# Docker used to bind the socket file and leave a directory; then Hyprland
# cannot listen and games die. Only repair that path.
game_ensure_xwayland() {
  if [ -S /tmp/.X11-unix/X0 ]; then
    return 0
  fi
  if [ -d /tmp/.X11-unix/X0 ]; then
    docker run --rm --user 0 --entrypoint /bin/rmdir \
      -v /tmp/.X11-unix:/tmp/.X11-unix steam-box:1 /tmp/.X11-unix/X0 >/dev/null 2>&1 || true
  fi
  rm -f /tmp/.X11-unix/X0 2>/dev/null || true
  if systemctl --user is-active aurora-xwayland.service >/dev/null 2>&1; then
    systemctl --user stop aurora-xwayland.service >/dev/null 2>&1 || true
  fi
}

# One container (`steam`) owns the library. Games are processes inside it.
# Drop the old per-game containers. Never stop the Steam client here.
game_ensure_steam() {
  local compose="${COMPOSE:-${HOME:-/home/dd}/.local/share/aurora/containers/steam/compose.yml}"
  local i
  docker rm -f overwatch terraria albion >/dev/null 2>&1 || true
  docker compose -f "$compose" up -d --no-deps --no-build steam
  for i in $(seq 1 40); do
    if docker inspect -f '{{.State.Running}}' steam 2>/dev/null | grep -qx true; then
      return 0
    fi
    sleep 0.25
  done
  echo "game-lib: steam container did not start" >&2
  return 1
}

game_stop_other_boxes() {
  local keep=${1:-}
  docker rm -f overwatch terraria albion >/dev/null 2>&1 || true
  case "$keep" in
    overwatch)
      pkill -x Terraria.exe >/dev/null 2>&1 || true
      pkill -x Terraria.bin >/dev/null 2>&1 || true
      pkill -x Albion-Online >/dev/null 2>&1 || true
      pkill -x AlbionOnline >/dev/null 2>&1 || true
      pkill -x AlienShooter.exe >/dev/null 2>&1 || true
      ;;
    terraria)
      pkill -x Overwatch.exe >/dev/null 2>&1 || true
      pkill -x Albion-Online >/dev/null 2>&1 || true
      pkill -x AlbionOnline >/dev/null 2>&1 || true
      pkill -x AlienShooter.exe >/dev/null 2>&1 || true
      ;;
    albion)
      pkill -x Overwatch.exe >/dev/null 2>&1 || true
      pkill -x Terraria.exe >/dev/null 2>&1 || true
      pkill -x Terraria.bin >/dev/null 2>&1 || true
      pkill -x AlienShooter.exe >/dev/null 2>&1 || true
      ;;
    alien-shooter)
      pkill -x Overwatch.exe >/dev/null 2>&1 || true
      pkill -x Terraria.exe >/dev/null 2>&1 || true
      pkill -x Terraria.bin >/dev/null 2>&1 || true
      pkill -x Albion-Online >/dev/null 2>&1 || true
      pkill -x AlbionOnline >/dev/null 2>&1 || true
      ;;
  esac
}

game_block_fossilize() {
  # Do not pkill fossilize_replay: Steam owns the Play-time compile.
  # Only pin launch options (albion.sh). Never wipe shader caches here.
  if [ -x "${BASH_SOURCE[0]%/*}/protect-shader-caches.sh" ]; then
    "${BASH_SOURCE[0]%/*}/protect-shader-caches.sh" >/dev/null 2>&1 || true
  fi
  if [ -x "${BASH_SOURCE[0]%/*}/steam-lock-shaders.sh" ]; then
    "${BASH_SOURCE[0]%/*}/steam-lock-shaders.sh" >/dev/null 2>&1 || true
  fi
  if [ -x "${BASH_SOURCE[0]%/*}/cap-fossilize.sh" ]; then
    "${BASH_SOURCE[0]%/*}/cap-fossilize.sh" >/dev/null 2>&1 || true
  fi
}

game_strip_overlay() {
  [ -n "${LD_PRELOAD:-}" ] || return 0
  local filtered="" p old_ifs=$IFS
  IFS=:
  for p in $LD_PRELOAD; do
    case "$p" in
      *gameoverlayrenderer*) ;;
      "") ;;
      *)
        if [ -z "$filtered" ]; then
          filtered=$p
        else
          filtered="$filtered:$p"
        fi
        ;;
    esac
  done
  IFS=$old_ifs
  export LD_PRELOAD="$filtered"
}

game_low_latency() {
  export __GL_SYNC_TO_VBLANK=0
  export vblank_mode=0
  # Steam client pins SDL to X11. Wrappers that want X11 set it again after this.
  unset SDL_VIDEODRIVER || true
}

# nvidia-settings inside the box has no NV-CONTROL, and on this driver
# GPUPowerMizerMode=1 is accepted and then stays 0. The card then sits
# near 1700 MHz / 20W while Overwatch is open, so the 200 Hz panel starves.
# Call this on the host session before the container starts.
game_gpu_perf() {
  DISPLAY="${DISPLAY:-:0}" \
    nvidia-settings -a "[gpu:0]/GPUPowerMizerMode=1" >/dev/null 2>&1 || true
  timeout 2 run0 nvidia-smi -lgc 2700,3090 >/dev/null 2>&1 || true
}

game_gpu_idle() {
  timeout 2 run0 nvidia-smi -rgc >/dev/null 2>&1 || true
}

# argv --safe-mode stays after rice restore. Only the autogenerated
# recoverycfg means stretch/fullscreen must be skipped.
game_hypr_broken() {
  local xdg="${HOST_XDG_RUNTIME_DIR:-${XDG_RUNTIME_DIR:-/run/user/1000}}"
  local sig="${HYPRLAND_INSTANCE_SIGNATURE:-}"
  local cfg
  if [ -z "$sig" ] && [ -d "$xdg/hypr" ]; then
    sig=$(find "$xdg/hypr" -mindepth 1 -maxdepth 1 -type d -printf '%T@ %f\n' 2>/dev/null | sort -nr | awk 'NR==1{print $2}')
  fi
  [ -n "$sig" ] || return 1
  cfg="$xdg/hypr/$sig/recoverycfg.lua"
  [ -f "$cfg" ] || return 1
  grep -q 'autogenerated = true' "$cfg" 2>/dev/null
}

# Drop compositor extras while a game box is up. Do not touch monitors.
game_compositor_game() {
  local on=${1:-1} fps blur
  # keyword/batch does not apply under the Lua config. hl.config does.
  if [ "$on" = 1 ]; then
    fps=200
    blur=false
    kill -STOP "$(pgrep -f '/mpvpaper ' | head -1)" >/dev/null 2>&1 || true
  else
    fps=15
    blur=true
    kill -CONT "$(pgrep -f '/mpvpaper ' | head -1)" >/dev/null 2>&1 || true
  fi
  local lua="hl.config({ misc = { render_unfocused_fps = $fps }, decoration = { blur = { enabled = $blur }, shadow = { enabled = $blur } } })"
  if [ -n "${STEAM_CONTAINER:-}" ] || [ -f /.dockerenv ]; then
    game_host hyprctl eval "$lua" >/dev/null 2>&1 || true
  else
    hyprctl eval "$lua" >/dev/null 2>&1 || true
  fi
}

game_gamescope() {
  local wrapped=/run/wrappers/bin/gamescope
  local plain=/run/current-system/sw/bin/gamescope
  # Steam's FHS bwrap cannot inherit NixOS file caps. After the 13 Sep
  # wrapper rebuild that prints "failed to inherit capabilities" and
  # exits, the game dies in ~4s and Steam thinks it closed.
  if [ -z "${SteamAppId:-}${SteamGameId:-}${STEAM_COMPAT_CLIENT_INSTALL_PATH:-}" ] && [ -x "$wrapped" ]; then
    echo "$wrapped"
    return 0
  fi
  if [ -x "$plain" ]; then
    echo "$plain"
    return 0
  fi
  if command -v gamescope >/dev/null 2>&1; then
    command -v gamescope
    return 0
  fi
  return 1
}

# Re-modeset only when a monitor actually drifted. hl.monitor on an
# already-correct HDMI is a full DRM modeset — that is what made the
# Philips change resolution every Overwatch launch.
game_outputs_ok() {
  game_host hyprctl monitors -j 2>/dev/null | awk '
    /"name": "HDMI-A-1"/ { t="h" }
    /"name": "DP-1"/ { t="d" }
    t=="h" && /"width": 1920/ { hw=1 }
    t=="h" && /"height": 1080/ { hh=1 }
    t=="h" && /"refreshRate": 60/ { hr=1 }
    t=="h" && /"x": 2560/ { hx=1 }
    t=="d" && /"width": 2560/ { dw=1 }
    t=="d" && /"height": 1080/ { dh=1 }
    t=="d" && /"refreshRate": 200/ { dr=1 }
    t=="d" && /"x": 0,/ { dx=1 }
    END { exit !(hw && hh && hr && hx && dw && dh && dr && dx) }
  '
}

game_pin_outputs() {
  game_outputs_ok && return 0
  game_host hyprctl eval '
hl.monitor({ output = "DP-1", mode = "2560x1080@200.00Hz", position = "0x0", scale = 1, bitdepth = 8, disabled = false })
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60.00Hz", position = "2560x0", scale = 1, bitdepth = 8, disabled = false })
' >/dev/null 2>&1 || true
}

game_xwayland_ultrawide() {
  game_pin_outputs
}

game_xwayland_restore() {
  game_pin_outputs
}

# Host binaries (hyprctl/qs) cannot see Steam's libstdc++ / libcurl.
# Inside steam-box XDG_RUNTIME_DIR is /tmp/xdg — point hyprctl at the real session.
game_host() {
  local xdg="${HOST_XDG_RUNTIME_DIR:-/run/user/1000}"
  local sig="${HYPRLAND_INSTANCE_SIGNATURE:-}"
  if [ -z "$sig" ] && [ -d "$xdg/hypr" ]; then
    sig=$(ls -1 "$xdg/hypr" 2>/dev/null | head -n1)
  fi
  env -u LD_PRELOAD -u LD_LIBRARY_PATH -u STEAM_RUNTIME_LIBRARY_PATH \
    PATH="/run/current-system/sw/bin:/etc/profiles/per-user/dd/bin" \
    XDG_RUNTIME_DIR="$xdg" \
    HYPRLAND_INSTANCE_SIGNATURE="$sig" \
    "$@"
}

game_place_overwatch() {
  # Repeating a move+fullscreen while Proton mapped a second surface put
  # the game on two workspaces. The compositor rule fullscreens one window.
  return 0
}

game_monitor() {
  game_host hyprctl monitors 2>/dev/null | awk '
    /^Monitor / { name = $2 }
    $1 ~ /^[0-9]+x[0-9]+@/ {
      split($1, r, /[x@]/)
      area = r[1] * r[2]
      if (area >= best) {
        best = area
        w = r[1]
        h = r[2]
        hz = r[3] + 0
        n = name
      }
    }
    END {
      if (n != "") printf "%s %s %d %s\n", w, h, hz, n
      else print "2560 1080 200 DP-1"
    }
  '
}

game_x_primary() {
  # RandR --primary on XWayland also hits the real HDMI CRTC. No-op.
  return 0
}

# SDL2-compat monitor index for the ultrawide (DP-1 2560x1080@200).
game_display_index() {
  local width=$1 height=$2
  command -v xrandr >/dev/null 2>&1 || { echo 0; return 0; }
  xrandr --listmonitors 2>/dev/null | awk -v tw="$width" -v th="$height" '
    NR > 1 {
      idx = $1
      gsub(/:/, "", idx)
      split($3, a, /[\/x+]/)
      if (a[1] + 0 == tw && a[3] + 0 == th) { print idx; exit }
    }
    END { if (NR) {} }
  '
}

game_wine_warp() {
  local reg=$1
  local mode=${2:-disable}
  [ -f "$reg" ] || return 0
  if grep -q 'MouseWarpOverride' "$reg"; then
    sed -i "s/\"MouseWarpOverride\"=\"[^\"]*\"/\"MouseWarpOverride\"=\"${mode}\"/" "$reg"
  elif grep -q '\[Software\\\\Wine\\\\X11 Driver\]' "$reg"; then
    sed -i "/\[Software\\\\Wine\\\\X11 Driver\]/a \"MouseWarpOverride\"=\"${mode}\"\n\"GrabFullscreen\"=\"N\"" "$reg"
  else
    printf '\n[Software\\\\Wine\\\\X11 Driver]\n"MouseWarpOverride"="%s"\n"GrabFullscreen"="N"\n' "$mode" >>"$reg"
  fi
  if grep -q 'GrabFullscreen' "$reg"; then
    sed -i 's/"GrabFullscreen"="[^"]*"/"GrabFullscreen"="N"/' "$reg"
  fi
  # XWayland lists HDMI as output 0. Wine RandR then modesets the Philips.
  if grep -q 'UseXRandR' "$reg"; then
    sed -i 's/"UseXRandR"="[^"]*"/"UseXRandR"="N"/' "$reg"
  elif grep -q '\[Software\\\\Wine\\\\X11 Driver\]' "$reg"; then
    sed -i '/\[Software\\\\Wine\\\\X11 Driver\]/a "UseXRandR"="N"\n"UseXVidMode"="N"' "$reg"
  fi
  if grep -q 'UseXVidMode' "$reg"; then
    sed -i 's/"UseXVidMode"="[^"]*"/"UseXVidMode"="N"/' "$reg"
  fi
}

# game_ini_set FILE SECTION KEY VALUE
# VALUE is written as-is after "=" (include quotes if the game wants them).
game_ini_set() {
  local file=$1 section=$2 key=$3 val=$4
  local tmp
  mkdir -p "$(dirname "$file")"
  [ -f "$file" ] || printf '%s\n' "$section" >"$file"
  tmp=$(mktemp)
  awk -v sect="$section" -v key="$key" -v val="$val" '
    function emit() { print key "=" val }
    {
      line = $0
      sub(/\r$/, "", line)
      if (line ~ /^\[.*\]$/) {
        if (insec && !done) emit()
        insec = (line == sect)
        print line
        next
      }
      if (insec) {
        split(line, parts, "=")
        k = parts[1]
        gsub(/^[ \t]+|[ \t]+$/, "", k)
        if (k == key) {
          # First hit wins; drop spaced/duplicate keys the game rewrites.
          if (!done) {
            emit()
            done = 1
          }
          next
        }
      }
      print line
    }
    END {
      if (!done) {
        if (!insec) print sect
        emit()
      }
    }
  ' "$file" >"$tmp" && mv "$tmp" "$file"
}

# Biggest on-disk copy of one Overwatch pipeline depot (download dir or final).
game_ow_hash_bytes() {
  local hash=$1 root
  root=/steam/steamapps/shadercache/2357570
  [ -d "$root" ] || root="${HOME:-/home/dd}/.local/share/Steam/steamapps/shadercache/2357570"
  find "$root" -path "*${hash}*" -name steam_pipeline_cache.foz -printf '%s\n' 2>/dev/null \
    | LC_ALL=C awk 'BEGIN{m=0} {if ($1+0>m) m=$1+0} END{printf "%.0f\n", m}'
}

game_fossil_alive() {
  local d comm
  for d in /proc/[0-9]*; do
    comm=$(cat "$d/comm" 2>/dev/null) || continue
    case "$comm" in
      fossilize_replay|fossilize-replay) return 0 ;;
    esac
  done
  return 1
}

# Steam applaunch starts the exe while these depots are still downloading.
# Block until both pipeline caches are on disk and a replay is not running.
game_wait_ow_shaders() {
  local need_a=12500000000 need_b=1300000000
  local i=0 a b k waited=0
  a=$(game_ow_hash_bytes 904f69d2b1b44b65)
  b=$(game_ow_hash_bytes 2e6c105801134e9c)
  if [ "$a" -lt "$need_a" ] || [ "$b" -lt "$need_b" ]; then
    waited=1
    while [ "$i" -lt 1800 ]; do
      a=$(game_ow_hash_bytes 904f69d2b1b44b65)
      b=$(game_ow_hash_bytes 2e6c105801134e9c)
      if [ "$a" -ge "$need_a" ] && [ "$b" -ge "$need_b" ]; then
        echo "game-lib: shader depots ready ($a $b)" >&2
        break
      fi
      if [ $((i % 15)) -eq 0 ]; then
        echo "game-lib: waiting for shader cache $a/$need_a $b/$need_b" >&2
      fi
      i=$((i + 1))
      sleep 2
    done
  fi
  a=$(game_ow_hash_bytes 904f69d2b1b44b65)
  b=$(game_ow_hash_bytes 2e6c105801134e9c)
  if [ "$a" -lt "$need_a" ] || [ "$b" -lt "$need_b" ]; then
    echo "game-lib: shader cache not ready, not launching" >&2
    return 1
  fi
  if [ "$waited" -eq 1 ]; then
    k=0
    while [ "$k" -lt 15 ]; do
      if game_fossil_alive; then
        break
      fi
      k=$((k + 1))
      sleep 1
    done
  fi
  if game_fossil_alive; then
    echo "game-lib: waiting for pipeline replay" >&2
    while game_fossil_alive; do
      sleep 2
    done
  fi
  return 0
}
