#!/run/current-system/sw/bin/bash
# Watchdog --safe-mode writes recoverycfg.lua (wiki example: preferred
# modes, HDMI at 0x0). Point that file at the real rice and reload.
set +e
export PATH="/run/current-system/sw/bin:/etc/profiles/per-user/dd/bin:${PATH:-}"
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
export WAYLAND_DISPLAY="${WAYLAND_DISPLAY:-wayland-1}"
unset LD_PRELOAD LD_LIBRARY_PATH STEAM_RUNTIME_LIBRARY_PATH || true

HYPRCTL="${HYPRCTL:-/run/current-system/sw/bin/hyprctl}"
HOME="${HOME:-/home/dd}"
REAL="${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hyprland.lua"
[ -f "$REAL" ] || exit 0

HIS="${HYPRLAND_INSTANCE_SIGNATURE:-}"
if [ -z "$HIS" ]; then
  HIS=$("$HYPRCTL" instances 2>/dev/null | awk '/^instance /{print $2; exit}' | tr -d ':')
fi
if [ -z "$HIS" ] && [ -d "${XDG_RUNTIME_DIR}/hypr" ]; then
  HIS=$(find "${XDG_RUNTIME_DIR}/hypr" -name '.socket.sock' -printf '%T@ %h\n' 2>/dev/null | sort -nr | awk 'NR==1{print $2}' | xargs -r basename)
fi
[ -n "$HIS" ] || exit 0
export HYPRLAND_INSTANCE_SIGNATURE=$HIS

cfg="${XDG_RUNTIME_DIR}/hypr/${HIS}/recoverycfg.lua"
stub=$(cat <<EOF
hl.config({ autogenerated = false })
local cfg = (os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config")) .. "/hypr"
package.path = cfg .. "/?.lua;" .. cfg .. "/?/init.lua;" .. (package.path or "")
dofile(cfg .. "/hyprland.lua")
EOF
)

need_reload=0
if [ -f "$cfg" ] && grep -q 'autogenerated = true' "$cfg" 2>/dev/null; then
  need_reload=1
fi
if [ -f "$cfg" ] && ! grep -q 'hyprland.lua' "$cfg" 2>/dev/null; then
  need_reload=1
fi
printf '%s\n' "$stub" >"$cfg"

"$HYPRCTL" eval 'hl.config({ autogenerated = false })' >/dev/null 2>&1 || true

if [ "$need_reload" = 1 ]; then
  "$HYPRCTL" reload >/dev/null 2>&1 || true
fi

"$HYPRCTL" eval 'hl.config({ autogenerated = false })' >/dev/null 2>&1 || true
# DP first at 0x0 so HDMI never overlaps the ultrawide.
"$HYPRCTL" eval 'hl.monitor({ output = "DP-1", mode = "2560x1080@200.00Hz", position = "0x0", scale = 1, bitdepth = 8, disabled = false })' >/dev/null 2>&1 || true
"$HYPRCTL" eval 'hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60.00Hz", position = "2560x0", scale = 1, bitdepth = 8, disabled = false })' >/dev/null 2>&1 || true
exit 0
