#!/usr/bin/env bash
# Host launcher: Overwatch runs in containers/steam service `overwatch`.
# Steam launch options (inside the box): /home/dd/.config/scripts/overwatch.sh %command%
set -euo pipefail

HOME="${HOME:-/home/dd}"
COMPOSE="${HOME}/containers/steam/compose.yml"
# shellcheck source=/dev/null
. "${BASH_SOURCE[0]%/*}/game-lib.sh"

in_box=0
if [ -n "${STEAM_CONTAINER:-}" ] || [ -f /.dockerenv ]; then
  in_box=1
fi

# ── Host path: only docker; never run Proton/OW on the host. ─────────────
if [ "$in_box" -eq 0 ]; then
  # Do not touch the compositor until the shader depots are on disk.
  # applaunch otherwise starts Overwatch while Steam is still downloading.
  game_wait_ow_shaders
  if [ -x "${BASH_SOURCE[0]%/*}/protect-shader-caches.sh" ]; then
    "${BASH_SOURCE[0]%/*}/protect-shader-caches.sh" >/dev/null 2>&1 || true
  fi

  # One library lock: Steam UI, Terraria and Albion must be down.
  game_ensure_xwayland
  game_stop_other_boxes overwatch
  game_gpu_perf
  # Plugin + fullscreen pin segfaulted Hyprland into safe-mode. Do not
  # load either until the compositor is a normal session again.
  if ! game_hypr_broken; then
    game_compositor_game 1
    if [ -x "${BASH_SOURCE[0]%/*}/ow-stretch-plugin.sh" ]; then
      FORCE=1 "${BASH_SOURCE[0]%/*}/ow-stretch-plugin.sh" --force >/dev/null 2>&1 || true
    fi
  fi

  mkdir -p "${HOME}/programs/steam"
  game_ensure_steam
  # Same container as the Steam window. Do not start a second box.
  docker exec steam /usr/local/bin/game-session.sh 2357570 Overwatch.exe
  status=$?
  game_compositor_game 0
  game_gpu_idle
  exit "$status"
fi

# ── Inside overwatch/steam box (launch options %command%). ───────────────

# Safe-mode means the last session segfaulted. Aborting here is why the
# game never appears. Skip the plugin and the fullscreen pin: that pin is
# what crashed Hyprland (setFullscreenMode on activate).
ow_safe=0
if game_hypr_broken; then
  ow_safe=1
  echo "overwatch.sh: Hyprland recoverycfg still autogenerated, launching without plugin/fullscreen" >&2
fi

game_block_fossilize
game_low_latency

# Do not call gamemode-start / gamemoderun: aurora-game toggles kill HDMI,
# hyprsunset, and decorations — user wants both monitors untouched.
if [ "$ow_safe" -eq 0 ] && [ -x "${BASH_SOURCE[0]%/*}/ow-stretch-plugin.sh" ]; then
  FORCE=1 "${BASH_SOURCE[0]%/*}/ow-stretch-plugin.sh" --force >/dev/null 2>&1 || true
fi
if [ "$ow_safe" -eq 0 ]; then
  game_compositor_game 1
fi

# ── Flags from ProtonDB + DXVK#3813 + Valve/NVIDIA OW shader-cache reports ──
# https://www.protondb.com/app/2357570
# https://github.com/doitsujin/dxvk/issues/3813
# https://github.com/ValveSoftware/steam-for-linux/issues/11392
export PROTON_ENABLE_NVAPI="${PROTON_ENABLE_NVAPI:-1}"
export PROTON_HIDE_NVIDIA_GPU="${PROTON_HIDE_NVIDIA_GPU:-0}"
export PROTON_ENABLE_NGX_UPDATER=0
export PROTON_LOCAL_SHADER_CACHE=1
export DXVK_NVAPI_VKREFLEX=0
# Steam's fossilize layer is what reads the pipelines it already compiled.
# Leaving it off is why the match compiled a second cache.
# No /dev/ntsync on this host — fsync/esync only.
export PROTON_NO_NTSYNC=1
export WINEFSYNC=1
export WINEESYNC=1
export PROTON_NO_ESYNC=0
export PROTON_NO_FSYNC=0
export PROTON_NO_XALIA=1
export PROTON_USE_XALIA=0
export DXVK_FILTER_DEVICE_NAME="${DXVK_FILTER_DEVICE_NAME:-NVIDIA}"
if [ -f /run/opengl-driver/share/vulkan/icd.d/nvidia_icd.json ]; then
  export VK_DRIVER_FILES=/run/opengl-driver/share/vulkan/icd.d/nvidia_icd.json
  export VK_ICD_FILENAMES=/run/opengl-driver/share/vulkan/icd.d/nvidia_icd.json
fi
# Proton talks X11 to Hyprland's XWayland. Native Wayland (PROTON_ENABLE_WAYLAND)
# presents off the compositor and the stretch plugin never sees the buffer.
# This is not a second Xorg — only the compositor's XWayland socket.
unset WAYLAND_DISPLAY GBM_BACKEND NVD_BACKEND || true
export PROTON_ENABLE_WAYLAND=0
export SDL_VIDEODRIVER=x11
export GDK_BACKEND=x11
export QT_QPA_PLATFORM=xcb
egl_x11="/run/opengl-driver/share/egl/egl_external_platform.d"
if [ -f "$egl_x11/20_nvidia_xlib.json" ]; then
  export __EGL_EXTERNAL_PLATFORM_CONFIG_FILENAMES="$egl_x11/20_nvidia_xlib.json:$egl_x11/20_nvidia_xcb.json"
fi
export DXVK_HDR=0
export DXVK_STATE_CACHE=1
export __GL_SYNC_TO_VBLANK=0
# Driver thread does shader-cache work. Without it that work sits on DXVK's
# submit thread, that thread stays at 100%, and the GPU waits with nothing to draw.
export __GL_THREADED_OPTIMIZATIONS=1
export __GL_SYNC_DISPLAY_DEVICE="${__GL_SYNC_DISPLAY_DEVICE:-DP-1}"
export __GL_SHARPEN_ENABLE=0
export __GL_GSYNC_ALLOWED=0
export __GL_VRR_ALLOWED=0
unset __GL_MaxFramesAllowed || true
# A cap at the refresh rate sits on 200 and dips under it. Leave DXVK uncapped.
unset DXVK_FRAME_RATE || true
# Steam overlay Vulkan layer was on and compositing every frame.
unset ENABLE_VK_LAYER_VALVE_steam_overlay_1 || true
export DISABLE_VK_LAYER_VALVE_steam_overlay_1=1
export __GL_SHADER_DISK_CACHE=1
export __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1

XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"

ow_dxvk_home="${XDG_CACHE_HOME}/dxvk/overwatch"
ow_dxvk_prefix="/steam/steamapps/compatdata/2357570/pfx/drive_c/users/steamuser/AppData/Local/dxvk"
# Driver looks up GLCache under this directory. This is Steam's own tree,
# the one fossilize_replay filled. Not a side copy.
ow_nv_cache="/steam/steamapps/shadercache/2357570/nvidiav1"
mkdir -p "$ow_dxvk_home" "$ow_dxvk_prefix" "$XDG_CONFIG_HOME/dxvk" "$ow_nv_cache"
if [ -x "${BASH_SOURCE[0]%/*}/protect-shader-caches.sh" ]; then
  "${BASH_SOURCE[0]%/*}/protect-shader-caches.sh" >/dev/null 2>&1 || true
fi
export DXVK_STATE_CACHE_PATH="$ow_dxvk_home"
export PROTON_DXVK_CONFIG_FILE="$XDG_CONFIG_HOME/dxvk/overwatch.conf"
export DXVK_CONFIG_FILE="$PROTON_DXVK_CONFIG_FILE"
export __GL_SHADER_DISK_CACHE_PATH="$ow_nv_cache"
export __GL_SHADER_DISK_CACHE=1
export __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1
export __GL_SHADER_DISK_CACHE_SIZE="${__GL_SHADER_DISK_CACHE_SIZE:-34359738368}"
export __GL_SHADER_DISK_CACHE_APP_NAME=steamapp_shader_cache
export __GL_SHADER_DISK_CACHE_READ_ONLY_APP_NAME="steam_shader_cache;steamapp_merged_shader_cache"

read -r phys_w phys_h refresh _ <<<"$(game_monitor)"
# In-game mode is 2560×1080 @ 200 Hz. 1920 is Full HD and the menu shows it.
width=2560
height=1080
refresh=200
use_219=0
# Cap above the 200 Hz panel so the counter is not glued to 200 and dipping under.
fps_cap=400

# Do not flip GPL. The disk cache was built without it; turning it on
# recompiles every pipeline on the CPU and the frame stutters.
cat >"$DXVK_CONFIG_FILE" <<EOF
dxgi.syncInterval = 0
dxvk.enableGraphicsPipelineLibrary = False
# Auto latency-sleep holds the GPU queue empty. Util stays near idle and
# frame time wobbles. Throughput, not the extra sleep.
dxvk.latencySleep = False
dxgi.nvLowLatency = False
EOF

ini="/steam/steamapps/compatdata/2357570/pfx/drive_c/users/steamuser/Documents/Overwatch/Settings/Settings_v0.ini"
game_ini_set "$ini" "[Render.13]" "FullScreenWidth" "\"${width}\""
game_ini_set "$ini" "[Render.13]" "FullScreenHeight" "\"${height}\""
game_ini_set "$ini" "[Render.13]" "WindowedWidth" "\"${width}\""
game_ini_set "$ini" "[Render.13]" "WindowedHeight" "\"${height}\""
game_ini_set "$ini" "[Render.13]" "FullScreenRefresh" "\"${refresh}\""
game_ini_set "$ini" "[Render.13]" "WindowedRefresh" "\"${refresh}\""
game_ini_set "$ini" "[GPU.6]" "DisplayIndex" "\"1\""
game_ini_set "$ini" "[Render.13]" "Use219AspectRatio" "\"${use_219}\""
# 0 = полный экран, 2560×1080 @ 200. 1 is borderless and the menu
# does not show fullscreen.
game_ini_set "$ini" "[Render.13]" "WindowMode" "\"0\""
game_ini_set "$ini" "[Render.13]" "FullscreenWindow" "\"0\""
game_ini_set "$ini" "[Render.13]" "FullscreenWindowEnabled" "\"0\""
game_ini_set "$ini" "[Render.13]" "FieldOfView" "\"103.000000\""
game_ini_set "$ini" "[Render.13]" "HorizontalFOV" "\"103.000000\""
game_ini_set "$ini" "[Render.13]" "BroadcastMarginBottom" "\"1.000000\""
game_ini_set "$ini" "[Render.13]" "BroadcastMarginLeft" "\"1.000000\""
game_ini_set "$ini" "[Render.13]" "BroadcastMarginRight" "\"1.000000\""
game_ini_set "$ini" "[Render.13]" "BroadcastMarginTop" "\"1.000000\""
game_ini_set "$ini" "[Render.13]" "LimitToRefresh" "\"0\""
game_ini_set "$ini" "[Render.13]" "UseVSync" "\"0\""
game_ini_set "$ini" "[Render.13]" "FrameRateCap" "\"${fps_cap}\""
game_ini_set "$ini" "[Render.13]" "ReduceBuffering" "\"0\""
game_ini_set "$ini" "[Render.13]" "TripleBufferingEnabled" "\"0\""
game_ini_set "$ini" "[Render.13]" "CpuForceSyncEnabled" "\"0\""
game_ini_set "$ini" "[Render.13]" "NVIDIAReflex" "\"0\""
game_ini_set "$ini" "[Render.13]" "ReflexMode" "\"0\""
# OW mirrors some Render keys into TankMenuItems; the spaced copy was
# capping at 205 while Render said 300.
game_ini_set "$ini" "[TankMenuItems.1]" "FrameRateCap" "\"${fps_cap}\""
game_ini_set "$ini" "[TankMenuItems.1]" "Use219AspectRatio" "\"${use_219}\""
game_ini_set "$ini" "[TankMenuItems.1]" "FullScreenWidth" "\"${width}\""
game_ini_set "$ini" "[TankMenuItems.1]" "FullScreenHeight" "\"${height}\""
game_ini_set "$ini" "[TankMenuItems.1]" "WindowedWidth" "\"${width}\""
game_ini_set "$ini" "[TankMenuItems.1]" "WindowedHeight" "\"${height}\""
game_ini_set "$ini" "[TankMenuItems.1]" "UseVSync" "\"0\""
game_ini_set "$ini" "[TankMenuItems.1]" "LimitToRefresh" "\"0\""
game_ini_set "$ini" "[Input.1]" "HighTickInput" "\"1\""

game_wine_warp "/steam/steamapps/compatdata/2357570/pfx/user.reg" disable
game_pin_outputs
game_strip_overlay
if [ "$ow_safe" -eq 0 ]; then
  game_place_overwatch
fi

if [ "$#" -eq 0 ]; then
  echo "overwatch.sh: inside box but no command" >&2
  exit 1
fi

# Prefer D3D11→DXVK (ProtonDB); skip if user/Steam already passed -dx11/-dx12.
has_dx=0
for a in "$@"; do
  case "$a" in
  -dx11 | -dx12) has_dx=1 ;;
  esac
done
if [ "$has_dx" -eq 0 ]; then
  set -- "$@" -dx11
fi

# Play in the Steam window hits this script directly. Same gate.
game_wait_ow_shaders

"$@"
status=$?
exit "$status"
