#!/usr/bin/env bash
# Host launcher: Overwatch runs in containers/steam service `overwatch`.
# Steam launch options (inside the box): /home/dd/.config/scripts/overwatch.sh %command%
#
# LOCKED picture (do not flip):
#   16:9 @ 1920×1080 windowed, Use219=0, WindowMode=1
#   csgo-vulkan-fix 1920×1080 + fix_mouse
#   Hyprland fullscreen 2 0 (internal exclusive, client windowed)
#   expand_undersized=true, nearest=false
#   Wine virtual desktop OFF (it invents a 60 Hz display)
#   Panel stays 2560×1080@200 — never modeset 1920
set -euo pipefail

HOME="${HOME:-/home/dd}"
COMPOSE="${HOME}/containers/steam/compose.yml"
# shellcheck source=/dev/null
. "${BASH_SOURCE[0]%/*}/game-lib.sh"

in_box=0
if [ -n "${STEAM_CONTAINER:-}" ] || [ -f /.dockerenv ]; then
  in_box=1
fi

# ── Host path: only docker; never run Proton/OW on the host. ─────────────
if [ "$in_box" -eq 0 ]; then
  game_fix_shadercache_bind
  game_skip_ow_shader_update
  if [ -x "${BASH_SOURCE[0]%/*}/protect-shader-caches.sh" ]; then
    "${BASH_SOURCE[0]%/*}/protect-shader-caches.sh" >/dev/null 2>&1 || true
  fi
  if [ -x "${BASH_SOURCE[0]%/*}/hypr-window-shade.sh" ]; then
    "${BASH_SOURCE[0]%/*}/hypr-window-shade.sh" unload >/dev/null 2>&1 || true
  fi
  if [ -x "${BASH_SOURCE[0]%/*}/hypr-csgo-vulkan-fix.sh" ]; then
    "${BASH_SOURCE[0]%/*}/hypr-csgo-vulkan-fix.sh" ensure >/dev/null 2>&1 || true
  fi

  pkill -STOP -f '/aurora fossilize loop' >/dev/null 2>&1 || true
  pkill -f 'fossilize_replay' >/dev/null 2>&1 || true
  pkill -STOP -f 'awww-daemon' >/dev/null 2>&1 || true

  game_ensure_xwayland
  game_xwayland_ultrawide
  game_stop_other_boxes overwatch
  game_gpu_perf
  if ! game_hypr_broken; then
    game_compositor_game 1
  fi
  mkdir -p "${HOME}/.local/state"
  : >"${HOME}/.local/state/aurora-game"

  mkdir -p "${HOME}/programs/steam"
  game_ensure_steam
  docker exec steam /usr/local/bin/game-session.sh 2357570 Overwatch.exe
  status=$?
  game_compositor_game 0
  rm -f "${HOME}/.local/state/aurora-game"
  game_gpu_idle
  if [ -x "${BASH_SOURCE[0]%/*}/hypr-window-shade.sh" ] && ! pgrep -x Overwatch.exe >/dev/null 2>&1; then
    "${BASH_SOURCE[0]%/*}/hypr-window-shade.sh" load >/dev/null 2>&1 || true
  fi
  pkill -CONT -f '/aurora fossilize loop' >/dev/null 2>&1 || true
  pkill -CONT -f 'awww-daemon' >/dev/null 2>&1 || true
  exit "$status"
fi

# ── Inside overwatch/steam box (launch options %command%). ───────────────

# Safe-mode means the last session segfaulted. Aborting here is why the
# game never appears. Skip the plugin and the fullscreen pin: that pin is
# what crashed Hyprland (setFullscreenMode on activate).
ow_safe=0
if game_hypr_broken; then
  ow_safe=1
  echo "overwatch.sh: Hyprland recoverycfg still autogenerated, launching without plugin/fullscreen" >&2
fi

game_block_fossilize
game_low_latency

# HyprWindowShade tags remap the cursor and eat clicks. Always unload
# before Proton maps the window — leftover tags survive across launches.
if [ -x "${BASH_SOURCE[0]%/*}/hypr-window-shade.sh" ]; then
  game_host "${BASH_SOURCE[0]%/*}/hypr-window-shade.sh" unload >/dev/null 2>&1 || true
fi
if [ -x "${BASH_SOURCE[0]%/*}/hypr-csgo-vulkan-fix.sh" ]; then
  game_host "${BASH_SOURCE[0]%/*}/hypr-csgo-vulkan-fix.sh" ensure >/dev/null 2>&1 || true
fi
game_host hyprctl eval "(function()
  local open = os.getenv('HOME') .. '/.config/hypr/shaders/liixini/crosshatch/open.glsl'
  local close = os.getenv('HOME') .. '/.config/hypr/shaders/liixini/crosshatch/close.glsl'
  hl.window_rule({ name = 'ow-strip-shader-open', match = { class = '^steam_app_2357570\$' }, tag = '-shader_open:' .. open })
  hl.window_rule({ name = 'ow-strip-shader-close', match = { class = '^steam_app_2357570\$' }, tag = '-shader_close:' .. close })
  return true
end)()" >/dev/null 2>&1 || true
# Do not call gamemode-start / gamemoderun: aurora-game toggles kill HDMI,
# hyprsunset, and decorations — user wants both monitors untouched.
if [ "$ow_safe" -eq 0 ]; then
  game_compositor_game 1
else
  # Still pin the aurora-game flag so qs hides chrome; skip heavy hypr toggles.
  game_host mkdir -p "${HOME}/.local/state" >/dev/null 2>&1 || true
  game_host bash -c ": >\"${HOME}/.local/state/aurora-game\"" >/dev/null 2>&1 || true
fi

# ── Flags from ProtonDB + DXVK#3813 + Valve/NVIDIA OW shader-cache reports ──
# https://www.protondb.com/app/2357570
# https://github.com/doitsujin/dxvk/issues/3813
# https://github.com/ValveSoftware/steam-for-linux/issues/11392
export PROTON_ENABLE_NVAPI="${PROTON_ENABLE_NVAPI:-1}"
export PROTON_HIDE_NVIDIA_GPU="${PROTON_HIDE_NVIDIA_GPU:-0}"
export PROTON_ENABLE_NGX_UPDATER=0
export PROTON_LOCAL_SHADER_CACHE=1
export DXVK_NVAPI_VKREFLEX=0
# Steam's fossilize layer is what reads the pipelines it already compiled.
# Leaving it off is why the match compiled a second cache.
# No /dev/ntsync on this host — fsync/esync only.
export PROTON_NO_NTSYNC=1
export WINEFSYNC=1
export WINEESYNC=1
export PROTON_NO_ESYNC=0
export PROTON_NO_FSYNC=0
export PROTON_NO_XALIA=1
export PROTON_USE_XALIA=0
export DXVK_FILTER_DEVICE_NAME="${DXVK_FILTER_DEVICE_NAME:-NVIDIA}"
if [ -f /run/opengl-driver/share/vulkan/icd.d/nvidia_icd.json ]; then
  export VK_DRIVER_FILES=/run/opengl-driver/share/vulkan/icd.d/nvidia_icd.json
  export VK_ICD_FILENAMES=/run/opengl-driver/share/vulkan/icd.d/nvidia_icd.json
fi
# Proton talks X11 to Hyprland's XWayland. Native Wayland (PROTON_ENABLE_WAYLAND)
# presents off the compositor and the stretch plugin never sees the buffer.
# This is not a second Xorg — only the compositor's XWayland socket.
unset WAYLAND_DISPLAY GBM_BACKEND NVD_BACKEND || true
export PROTON_ENABLE_WAYLAND=0
export SDL_VIDEODRIVER=x11
export GDK_BACKEND=x11
export QT_QPA_PLATFORM=xcb
egl_x11="/run/opengl-driver/share/egl/egl_external_platform.d"
if [ -f "$egl_x11/20_nvidia_xlib.json" ]; then
  export __EGL_EXTERNAL_PLATFORM_CONFIG_FILENAMES="$egl_x11/20_nvidia_xlib.json:$egl_x11/20_nvidia_xcb.json"
fi
export DXVK_HDR=0
export DXVK_STATE_CACHE=1
export __GL_SYNC_TO_VBLANK=0
# Driver thread does shader-cache work. Without it that work sits on DXVK's
# submit thread, that thread stays at 100%, and the GPU waits with nothing to draw.
export __GL_THREADED_OPTIMIZATIONS=1
export __GL_SYNC_DISPLAY_DEVICE="${__GL_SYNC_DISPLAY_DEVICE:-DP-4}"
export __GL_SHARPEN_ENABLE=0
export __GL_GSYNC_ALLOWED=0
export __GL_VRR_ALLOWED=0
unset __GL_MaxFramesAllowed || true
# A cap at the refresh rate sits on 200 and dips under it. Leave DXVK uncapped.
unset DXVK_FRAME_RATE || true
# Steam overlay Vulkan layer was on and compositing every frame.
unset ENABLE_VK_LAYER_VALVE_steam_overlay_1 || true
export DISABLE_VK_LAYER_VALVE_steam_overlay_1=1
export __GL_SHADER_DISK_CACHE=1
export __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1

XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"

ow_dxvk_home="${XDG_CACHE_HOME}/dxvk/overwatch"
ow_dxvk_prefix="/steam/steamapps/compatdata/2357570/pfx/drive_c/users/steamuser/AppData/Local/dxvk"
# Driver looks up GLCache under this directory. This is Steam's own tree,
# the one fossilize_replay filled. Not a side copy.
ow_nv_cache="/steam/steamapps/shadercache/2357570/nvidiav1"
mkdir -p "$ow_dxvk_home" "$ow_dxvk_prefix" "$XDG_CONFIG_HOME/dxvk" "$ow_nv_cache"
if [ -x "${BASH_SOURCE[0]%/*}/protect-shader-caches.sh" ]; then
  "${BASH_SOURCE[0]%/*}/protect-shader-caches.sh" >/dev/null 2>&1 || true
fi
export DXVK_STATE_CACHE_PATH="$ow_dxvk_home"
export PROTON_DXVK_CONFIG_FILE="$XDG_CONFIG_HOME/dxvk/overwatch.conf"
export DXVK_CONFIG_FILE="$PROTON_DXVK_CONFIG_FILE"
export __GL_SHADER_DISK_CACHE_PATH="$ow_nv_cache"
export __GL_SHADER_DISK_CACHE=1
export __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1
export __GL_SHADER_DISK_CACHE_SIZE="${__GL_SHADER_DISK_CACHE_SIZE:-34359738368}"
export __GL_SHADER_DISK_CACHE_APP_NAME=steamapp_shader_cache
export __GL_SHADER_DISK_CACHE_READ_ONLY_APP_NAME="steam_shader_cache;steamapp_merged_shader_cache"

read -r phys_w phys_h phys_hz game_output <<<"$(game_monitor)"
# 16:9. Game stays windowed 1920; compositor + vulkan-fix stretch to 2560@200.
# Wine desktop is forbidden — it invents a 60 Hz display.
width=1920
height=1080
refresh=200
use_219=0

# The DP-4 default predates this box; the ultrawide is DP-1 and naming a
# connector that does not exist leaves the driver syncing to the 60 Hz HDMI.
export __GL_SYNC_DISPLAY_DEVICE="${game_output:-DP-1}"

# winepulse enumerates the GPU HDMI sink first and Overwatch latches onto
# it. Nothing is plugged in there, so the game is silent while the rest of
# the desktop keeps playing. Pin it to the sink the session actually uses.
if [ -z "${PULSE_SINK:-}" ]; then
  ow_sink=$(game_host wpctl inspect @DEFAULT_AUDIO_SINK@ 2>/dev/null \
    | awk -F'"' '/node\.name/ { print $2; exit }')
  if [ -n "$ow_sink" ]; then
    export PULSE_SINK="$ow_sink"
    echo "overwatch.sh: audio pinned to $ow_sink" >&2
  fi
fi

# XWayland orders outputs by monitor ID, so HDMI (ID 0) sits at X11 +0+0 and
# Overwatch picks it: it then renders 1920x1080@60 and the compositor
# stretches that into 2560x1080 — blurred, horizontally squashed text, 60 Hz.
# Primary has to be set before the game enumerates displays.
game_xwayland_primary "$game_output"
# Index is the X11 output order, and --primary moves the ultrawide to 0.
display_index=0
# Do not sit on 200: one missed present becomes a hitch. Overlay still shows real FPS.
fps_cap=0

# Do not flip GPL. The disk cache was built without it; turning it on
# recompiles every pipeline on the CPU and the frame stutters.
cat >"$DXVK_CONFIG_FILE" <<EOF
dxgi.syncInterval = 0
dxvk.enableGraphicsPipelineLibrary = False
# Auto latency-sleep holds the GPU queue empty. Util stays near idle and
# frame time wobbles. Throughput, not the extra sleep.
dxvk.latencySleep = False
dxgi.nvLowLatency = False
# 1 + compositor stretch waits on the released buffer and 200/100s.
# Two frames in flight keeps the DX11 submit thread from stalling.
dxvk.maxFrameLatency = 2
EOF

ini="/steam/steamapps/compatdata/2357570/pfx/drive_c/users/steamuser/Documents/Overwatch/Settings/Settings_v0.ini"
game_ini_set "$ini" "[Render.13]" "FullScreenWidth" "\"${width}\""
game_ini_set "$ini" "[Render.13]" "FullScreenHeight" "\"${height}\""
game_ini_set "$ini" "[Render.13]" "WindowedWidth" "\"${width}\""
game_ini_set "$ini" "[Render.13]" "WindowedHeight" "\"${height}\""
game_ini_set "$ini" "[Render.13]" "FullScreenRefresh" "\"${refresh}\""
game_ini_set "$ini" "[Render.13]" "WindowedRefresh" "\"${refresh}\""
game_ini_set "$ini" "[GPU.6]" "DisplayIndex" "\"${display_index}\""
# 1.0 is "no scaling". Anything else is the driver resampling the frame.
game_ini_set "$ini" "[GPU.6]" "GPUScaler" "\"1.000000\""
game_ini_set "$ini" "[Render.13]" "Use219AspectRatio" "\"${use_219}\""
game_ini_set "$ini" "[Render.13]" "WindowMode" "\"1\""
game_ini_set "$ini" "[Render.13]" "FullscreenWindow" "\"0\""
game_ini_set "$ini" "[Render.13]" "FullscreenWindowEnabled" "\"0\""
game_ini_set "$ini" "[Render.13]" "FieldOfView" "\"103.000000\""
game_ini_set "$ini" "[Render.13]" "HorizontalFOV" "\"103.000000\""
game_ini_set "$ini" "[Render.13]" "BroadcastMarginBottom" "\"0.000000\""
game_ini_set "$ini" "[Render.13]" "BroadcastMarginLeft" "\"0.000000\""
game_ini_set "$ini" "[Render.13]" "BroadcastMarginRight" "\"0.000000\""
game_ini_set "$ini" "[Render.13]" "BroadcastMarginTop" "\"0.000000\""
game_ini_set "$ini" "[Render.13]" "LimitToRefresh" "\"0\""
game_ini_set "$ini" "[Render.13]" "UseVSync" "\"0\""
game_ini_set "$ini" "[Render.13]" "FrameRateCap" "\"${fps_cap}\""
# 1 made 1% lows worse under DXVK (submit thread already saturated).
game_ini_set "$ini" "[Render.13]" "ReduceBuffering" "\"0\""
game_ini_set "$ini" "[Render.13]" "TripleBufferingEnabled" "\"0\""
game_ini_set "$ini" "[Render.13]" "CpuForceSyncEnabled" "\"0\""
game_ini_set "$ini" "[Render.13]" "NVIDIAReflex" "\"0\""
game_ini_set "$ini" "[Render.13]" "ReflexMode" "\"0\""
# OW mirrors some Render keys into TankMenuItems; the spaced copy was
# capping at 205 while Render said 300.
# Without the counter there is no way to tell a single-thread CPU ceiling
# from an actual frame drop — GPU utilisation says nothing either way.
game_ini_set "$ini" "[TankMenuItems.1]" "FPSOverlay" "\"1\""
game_ini_set "$ini" "[TankMenuItems.1]" "FrameRateCap" "\"${fps_cap}\""
game_ini_set "$ini" "[TankMenuItems.1]" "Use219AspectRatio" "\"${use_219}\""
game_ini_set "$ini" "[TankMenuItems.1]" "FullScreenWidth" "\"${width}\""
game_ini_set "$ini" "[TankMenuItems.1]" "FullScreenHeight" "\"${height}\""
game_ini_set "$ini" "[TankMenuItems.1]" "WindowedWidth" "\"${width}\""
game_ini_set "$ini" "[TankMenuItems.1]" "WindowedHeight" "\"${height}\""
game_ini_set "$ini" "[TankMenuItems.1]" "UseVSync" "\"0\""
game_ini_set "$ini" "[TankMenuItems.1]" "LimitToRefresh" "\"0\""
game_ini_set "$ini" "[Input.1]" "HighTickInput" "\"1\""

game_wine_warp "/steam/steamapps/compatdata/2357570/pfx/user.reg" disable
game_wine_desktop_off "/steam/steamapps/compatdata/2357570/pfx/user.reg"
# Re-pinning the outputs can drop the X11 primary flag, so re-assert it.
game_xwayland_ultrawide
game_strip_overlay
if [ "$ow_safe" -eq 0 ]; then
  game_place_overwatch
fi

if [ "$#" -eq 0 ]; then
  echo "overwatch.sh: inside box but no command" >&2
  exit 1
fi

# OW on this Proton build ignores -dx12 (log still says Dx11). Keep -dx11
# honest and spend the budget on DXVK_FRAME_RATE + fps_cap pacing instead.
out=()
for a in "$@"; do
  case "$a" in
  -dx11 | -dx12) continue ;;
  *) out+=("$a") ;;
  esac
done
set -- "${out[@]}"
set -- "$@" -dx11 -windowed -w "${width}" -h "${height}"

game_skip_ow_shader_update

"$@"
status=$?
game_compositor_game 0
exit "$status"
