[general]
early-exit = ["all"]
copy-command = "wl-copy"
annotation-size-factor = 1.0
actions-on-enter = ["save-to-clipboard", "save-to-file"]
actions-on-escape = ["save-to-clipboard", "exit"]
notification-thumbnail = "app-icon"
corner-roundness = 12
initial-tool = "brush"
no-window-decoration = true
