package hyprfix

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"aurora/internal/execx"
	"aurora/internal/wallpaper"
)

const stub = `hl.config({ autogenerated = false })
local cfg = (os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config")) .. "/hypr"
package.path = cfg .. "/?.lua;" .. cfg .. "/?/init.lua;" .. (package.path or "")
dofile(cfg .. "/hyprland.lua")
`

func rice() string {
	cfg := os.Getenv("XDG_CONFIG_HOME")
	if cfg == "" {
		cfg = filepath.Join(execx.Home(), ".config")
	}
	return filepath.Join(cfg, "hypr", "hyprland.lua")
}

func his() string {
	// systemd keeps a dead HIS after watchdog --safe-mode. Always ask
	// the live compositor first.
	_, out := execx.Run(2*time.Second, "hyprctl", "instances")
	for _, line := range strings.Split(out, "\n") {
		if strings.HasPrefix(line, "instance ") {
			return strings.Trim(strings.Fields(line)[1], ":")
		}
	}
	if h := os.Getenv("HYPRLAND_INSTANCE_SIGNATURE"); h != "" {
		sock := filepath.Join(execx.Runtime(), "hypr", h, ".socket.sock")
		if _, err := os.Stat(sock); err == nil {
			return h
		}
	}
	base := filepath.Join(execx.Runtime(), "hypr")
	ents, err := os.ReadDir(base)
	if err != nil {
		return ""
	}
	var newest string
	var newestT time.Time
	for _, e := range ents {
		p := filepath.Join(base, e.Name(), ".socket.sock")
		st, err := os.Stat(p)
		if err != nil {
			continue
		}
		if newest == "" || st.ModTime().After(newestT) {
			newest, newestT = e.Name(), st.ModTime()
		}
	}
	return newest
}

func recovery() string {
	h := his()
	if h == "" {
		return ""
	}
	return filepath.Join(execx.Runtime(), "hypr", h, "recoverycfg.lua")
}

func Loaded() bool {
	cfg := recovery()
	if cfg == "" {
		return false
	}
	b, err := os.ReadFile(cfg)
	if err != nil {
		return false
	}
	s := string(b)
	return strings.Contains(s, "hyprland.lua") && !strings.Contains(s, "autogenerated = true")
}

type monJSON struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Width       int     `json:"width"`
	Height      int     `json:"height"`
	RefreshRate float64 `json:"refreshRate"`
	X           int     `json:"x"`
}

func monitors() []monJSON {
	_, out := execx.Run(2*time.Second, "hyprctl", "monitors", "-j")
	var ms []monJSON
	_ = json.Unmarshal([]byte(out), &ms)
	return ms
}

// NVIDIA connector names jump (DP-1↔DP-4, HDMI-A-1↔HDMI-A-2). Resolve
// the live Xiaomi ultrawide + Philips secondary by name or description.
func findOutputs(ms []monJSON) (hdmi, dp *monJSON) {
	for i := range ms {
		m := &ms[i]
		n := m.Name
		d := m.Description
		switch {
		case n == "HDMI-A-2" || n == "HDMI-A-1" ||
			strings.Contains(d, "PHL") || strings.Contains(d, "Philips"):
			hdmi = m
		case n == "DP-4" || n == "DP-1" ||
			strings.Contains(d, "Mi 30") || strings.Contains(d, "Xiaomi"):
			dp = m
		}
	}
	return hdmi, dp
}

func pinMonitor(name, mode, position string) {
	if name == "" {
		return
	}
	expr := fmt.Sprintf(
		`hl.monitor({ output = %q, mode = %q, position = %q, scale = 1, bitdepth = 8, disabled = false })`,
		name, mode, position,
	)
	_ = execx.RunOK(2*time.Second, "hyprctl", "eval", expr)
}

func pinLive() {
	ms := monitors()
	hdmi, dp := findOutputs(ms)
	dpName, hdmiName := "DP-1", "HDMI-A-1"
	if dp != nil && dp.Name != "" {
		dpName = dp.Name
	}
	if hdmi != nil && hdmi.Name != "" {
		hdmiName = hdmi.Name
	}
	pinMonitor(dpName, "2560x1080@200.00Hz", "0x0")
	pinMonitor(hdmiName, "1920x1080@60.00Hz", "2560x0")
}

func Recover() int {
	if _, err := os.Stat(rice()); err != nil {
		return 0
	}
	if Loaded() {
		pinIfDrifted()
		_ = wallpaper.Ensure()
		return 0
	}
	cfg := recovery()
	if cfg == "" {
		return 1
	}
	_ = os.WriteFile(cfg, []byte(stub), 0o644)
	_ = os.Setenv("HYPRLAND_INSTANCE_SIGNATURE", his())
	_ = execx.RunOK(2*time.Second, "hyprctl", "eval", `hl.config({ autogenerated = false, cursor = { no_hardware_cursors = true, use_cpu_buffer = false, enable_hyprcursor = false } })`)
	_ = execx.RunOK(2*time.Second, "hyprctl", "eval", `hl.config({ cursor = { no_hardware_cursors = true, use_cpu_buffer = false, enable_hyprcursor = false } })`)
	pinLive()
	if b, err := os.ReadFile(cfg); err == nil && strings.Contains(string(b), "autogenerated = true") {
		_ = os.WriteFile(cfg, []byte(stub), 0o644)
	}
	_ = execx.RunOK(8*time.Second, "hyprctl", "reload")
	_ = execx.RunOK(2*time.Second, "hyprctl", "eval", `hl.config({ autogenerated = false })`)
	_ = wallpaper.Ensure()
	if Loaded() {
		return 0
	}
	return 1
}

func outputsOK() bool {
	ms := monitors()
	hdmi, dp := findOutputs(ms)
	if hdmi == nil || dp == nil {
		return false
	}
	return hdmi.Width == 1920 && hdmi.Height == 1080 && hdmi.X == 2560 &&
		hdmi.RefreshRate > 58 && hdmi.RefreshRate < 61.5 &&
		dp.Width == 2560 && dp.Height == 1080 && dp.X == 0 &&
		dp.RefreshRate > 198 && dp.RefreshRate < 202
}

func pinIfDrifted() {
	if outputsOK() {
		return
	}
	pinLive()
}

func ensureQuickshell() {
	if execx.RunOK(400*time.Millisecond, "pgrep", "-x", "quickshell") {
		return
	}
	_ = execx.RunOK(2*time.Second, "systemctl", "--user", "reset-failed", "quickshell.service")
	_ = execx.RunOK(2*time.Second, "systemctl", "--user", "start", "quickshell.service")
}

func Watch() {
	for {
		if !Loaded() {
			_ = Recover()
			ensureQuickshell()
			time.Sleep(3 * time.Second)
			continue
		}
		_ = wallpaper.Ensure()
		ensureQuickshell()
		pinIfDrifted()
		if outputsOK() {
			time.Sleep(15 * time.Second)
			continue
		}
		time.Sleep(3 * time.Second)
	}
}

func Main(args []string) int {
	if len(args) > 0 && (args[0] == "loop" || args[0] == "watch") {
		Watch()
		return 0
	}
	_ = Recover()
	for _, w := range []time.Duration{200 * time.Millisecond, 500 * time.Millisecond, time.Second, 2 * time.Second, 4 * time.Second} {
		if Loaded() {
			_ = wallpaper.Ensure()
			return 0
		}
		time.Sleep(w)
		_ = Recover()
	}
	_ = wallpaper.Ensure()
	return 0
}
