package hyprfix

import (
	"os"
	"path/filepath"
	"strings"
	"time"

	"aurora/internal/execx"
	"aurora/internal/wallpaper"
)

const stub = `hl.config({ autogenerated = false })
local cfg = (os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config")) .. "/hypr"
package.path = cfg .. "/?.lua;" .. cfg .. "/?/init.lua;" .. (package.path or "")
dofile(cfg .. "/hyprland.lua")
`

func rice() string {
	cfg := os.Getenv("XDG_CONFIG_HOME")
	if cfg == "" {
		cfg = filepath.Join(execx.Home(), ".config")
	}
	return filepath.Join(cfg, "hypr", "hyprland.lua")
}

func his() string {
	if h := os.Getenv("HYPRLAND_INSTANCE_SIGNATURE"); h != "" {
		return h
	}
	_, out := execx.Run(2*time.Second, "hyprctl", "instances")
	for _, line := range strings.Split(out, "\n") {
		if strings.HasPrefix(line, "instance ") {
			return strings.Trim(strings.Fields(line)[1], ":")
		}
	}
	base := filepath.Join(execx.Runtime(), "hypr")
	ents, err := os.ReadDir(base)
	if err != nil {
		return ""
	}
	var newest string
	var newestT time.Time
	for _, e := range ents {
		p := filepath.Join(base, e.Name(), ".socket.sock")
		st, err := os.Stat(p)
		if err != nil {
			continue
		}
		if newest == "" || st.ModTime().After(newestT) {
			newest, newestT = e.Name(), st.ModTime()
		}
	}
	return newest
}

func recovery() string {
	h := his()
	if h == "" {
		return ""
	}
	return filepath.Join(execx.Runtime(), "hypr", h, "recoverycfg.lua")
}

func Loaded() bool {
	cfg := recovery()
	if cfg == "" {
		return false
	}
	b, err := os.ReadFile(cfg)
	if err != nil {
		return false
	}
	s := string(b)
	return strings.Contains(s, "hyprland.lua") && !strings.Contains(s, "autogenerated = true")
}

func Recover() int {
	if _, err := os.Stat(rice()); err != nil {
		return 0
	}
	if Loaded() {
		_ = wallpaper.Ensure()
		return 0
	}
	cfg := recovery()
	if cfg == "" {
		return 1
	}
	_ = os.WriteFile(cfg, []byte(stub), 0o644)
	_ = os.Setenv("HYPRLAND_INSTANCE_SIGNATURE", his())
	_ = execx.RunOK(2*time.Second, "hyprctl", "eval", `hl.config({ autogenerated = false, cursor = { no_hardware_cursors = true, use_cpu_buffer = false } })`)
	_ = execx.RunOK(2*time.Second, "hyprctl", "keyword", "cursor:no_hardware_cursors", "1")
	_ = execx.RunOK(2*time.Second, "hyprctl", "eval", `hl.monitor({ output = "DP-1", mode = "2560x1080@200.00Hz", position = "0x0", scale = 1, bitdepth = 8, disabled = false })`)
	_ = execx.RunOK(2*time.Second, "hyprctl", "eval", `hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60.00Hz", position = "2560x0", scale = 1, bitdepth = 8, disabled = false })`)
	if b, err := os.ReadFile(cfg); err == nil && strings.Contains(string(b), "autogenerated = true") {
		_ = os.WriteFile(cfg, []byte(stub), 0o644)
	}
	_ = execx.RunOK(8*time.Second, "hyprctl", "reload")
	_ = execx.RunOK(2*time.Second, "hyprctl", "eval", `hl.config({ autogenerated = false })`)
	_ = execx.RunOK(3*time.Second, filepath.Join(execx.Home(), ".config", "scripts", "ow-stretch-plugin.sh"), "load")
	_ = wallpaper.Ensure()
	if Loaded() {
		return 0
	}
	return 1
}

func Watch() {
	for {
		if !Loaded() {
			_ = Recover()
		} else {
			_ = wallpaper.Ensure()
		}
		time.Sleep(3 * time.Second)
	}
}

func Main(args []string) int {
	if len(args) > 0 && (args[0] == "loop" || args[0] == "watch") {
		Watch()
		return 0
	}
	_ = Recover()
	for _, w := range []time.Duration{200 * time.Millisecond, 500 * time.Millisecond, time.Second, 2 * time.Second, 4 * time.Second} {
		if Loaded() {
			_ = wallpaper.Ensure()
			return 0
		}
		time.Sleep(w)
		_ = Recover()
	}
	_ = wallpaper.Ensure()
	return 0
}
